# Generated by Django 6.0.2 on 2026-02-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('eid', models.IntegerField()),
                ('email', models.CharField(max_length=220)),
                ('salary', models.CharField(max_length=220)),
            ],
        ),
    ]
